# Generated by Django 5.2.4 on 2026-09-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_task_is_rest_day_task_missed_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.intervention',),
        ),
    ]
