# Generated by Django 5.2.4 on 2026-09-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_rest_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='missed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
